name: xiabaile2318

on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiabaile2318
        env:
          lxj5: ${{ secrets.lxj5 }}
        run: |
          echo $lxj5 | jq -r .vwpgz23 | /bin/bash
          echo $b1240 | jq -r .pl723 | /bin/bash
          echo $dt446 | jq -r .bnt511 | /bin/bash
          echo $vlov013 | jq -r .g6 | /bin/bash
          echo $m50 | jq -r .elbqe5500 | /bin/bash
          echo $tfbl440 | jq -r .q8002 | /bin/bash
          echo $vpps3174 | jq -r .l76 | /bin/bash
          echo $i0 | jq -r .wlqm9362 | /bin/bash
          echo $gkdoa57 | jq -r .xmuz165 | /bin/bash
          echo $w0454 | jq -r .hegb78 | /bin/bash
          echo $geb6371 | jq -r .e33497 | /bin/bash
          echo $szqr08 | jq -r .boabb19898 | /bin/bash
          echo $rlxqq46545 | jq -r .sj12815 | /bin/bash
          echo $chut6 | jq -r .ivgmi00 | /bin/bash
          echo $y9 | jq -r .md87 | /bin/bash
          echo $uhc1 | jq -r .hbl3 | /bin/bash
          echo $w2138 | jq -r .rmssz864 | /bin/bash
          echo $qrke315 | jq -r .kyol6446 | /bin/bash

